# Generated by Django 4.1.2 on 2022-10-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Middle_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Surname', models.CharField(max_length=100)),
                ('Northing1', models.FloatField()),
                ('Easting1', models.FloatField()),
                ('Northing2', models.FloatField()),
                ('Easting2', models.FloatField()),
                ('Northing3', models.FloatField()),
                ('Easting3', models.FloatField()),
                ('Northing4', models.FloatField()),
                ('Easting4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('password', models.SlugField()),
            ],
        ),
    ]
